### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'get')

### ISSUE THREAD

**Issue by vivekaris** [asantibanez/livewire-charts#71]
**Describe the bug**
   Uncaught TypeError: Cannot read properties of undefined (reading 'get')
    at Proxy.drawChart (app.js:3:472873)
    at app.js:3:472785

**To Reproduce**
1. '$columnChartModel = 
    (new ColumnChartModel())
        ->setTitle('Expenses by Type')
        ->addColumn('Food', 100, '#f6ad55')
        ->addColumn('Shopping', 200, '#fc8181')
        ->addColumn('Travel', 300, '#90cdf4')
    ;'
2. '<livewire:livewire-column-chart
    :column-chart-model="$columnChartModel"
/>'

3. 'Uncaught TypeError: Cannot read properties of undefined (reading 'get')
    at Proxy.drawChart (app.js:3:472873)
    at app.js:3:472785'

**Solution Ideas**
thinking

**Comment by Solotov** [comment]
_This is probably because Livewire is not properly initialized or not installed, follow these instructions:_

## Requirements

This package requires the following packages/libraries to work:
- `Laravel Livewire v2` (https://laravel-livewire.com/) 
- `Alpine Js` (https://github.com/alpinejs/alpine)
- `Apex Charts` (https://apexcharts.com/)

Please follow each package/library instructions on how to set them properly in your project.

Next, include the `@livewireChartsScripts` directive next to your other app scripts

```html
<livewire:scripts />
@livewireChartsScripts
```

**Comment by stojankukrika** [comment]
I get the same error. Even Livewire works well on other pages.
<img width="746" alt="Screenshot 2022-05-17 at 05 22 49" src="https://user-images.githubusercontent.com/10199584/168722041-e209402d-6710-4cea-a312-9d393f7a94d9.png">
I tried with local apexcharts:
 `<script src="{{asset('js/apexcharts.js')}}"></script>
 @livewireChartsScripts`
but error didn't disappear.

**Comment by hearthlytorepalma** [comment]
This was my issue 1hr ago. I just found out that I did not add `window.Alpine = Alpine` in my bundle after importing the Alpine module. 

I hope this helps.
