### ISSUE TITLE
livewireChartsColumnChart is not defined

### ISSUE THREAD

**Issue by spham** [asantibanez/livewire-charts#75]
Not display chart

**To Reproduce**
1. follow this README.md usage 
2. add @livewireChartsScripts in layout/app.blade.php
3. php artisan livewire:publish --assets
4. display source and see 404 can't reach generated public/vendor/livewire-charts/app.js
5. but in this directory, not have app.js, just 3 files livrewire.js, livrewire.js.map and manifest.json )

 

**Expected behavior**
Should see graphic

```
app.js:434 Uncaught ReferenceError: livewireChartsColumnChart is not defined
    at eval (eval at safeAsyncFunction (app.js:485:14), <anonymous>:3:16)
    at app.js:503:21
    at tryCatch (app.js:423:12)
    at evaluate (app.js:448:32)
    at app.js:2599:15
    at Function.<anonymous> (app.js:1166:55)
    at flushHandlers (app.js:560:46)
    at stopDeferring (app.js:565:5)
    at deferHandlingDirectives (app.js:568:3)
    at initTree (app.js:778:3)
app.js:434 Uncaught ReferenceError: init is not defined
    at eval (eval at safeAsyncFunction (app.js:485:14), <anonymous>:3:16)
    at app.js:503:21
    at tryCatch (app.js:423:12)
    at Function.evaluate (app.js:448:32)
    at app.js:2515:35
    at Function.<anonymous> (app.js:1166:55)
    at flushHandlers (app.js:560:46)
    at stopDeferring (app.js:565:5)
    at deferHandlingDirectives (app.js:568:3)
    at initTree (app.js:778:3)
```
**Screenshots**
![image](https://user-images.githubusercontent.com/1083631/166140197-e8883919-5f1f-4eea-89c3-797183c49e80.png)

**Additional context**
- composer.json
  - laravel 9 + breeze
  - asantibanez/livewire-charts : "^2.4"
  - laravel/framework : "^9.2"
- package.json
  - "apexcharts": "^3.35.0"

resource\app.js

```
require('./bootstrap');
import Alpine from 'alpinejs';
import ApexCharts from 'apexcharts'
window.Alpine = Alpine;
Alpine.start();
```

**Comment by Piket564** [comment]
How did you resolved?

**Comment by coolsam726** [comment]
How was this resolved? I am getting the error after upgrading to ^2.4

**Comment by MikePageDev** [comment]
I am getting the same error. How was it fixed?

**Comment by dominik-eller** [comment]
I am having the same after upgrading to laravel-vite 1.0.1 and Vite 5
